/content/drive/MyDrive/ML_Android/On New Data


In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [3]:
%cd /content/drive/MyDrive/ML_Android/On New Data

/content/drive/MyDrive/ML_Android/On New Data


In [4]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder, LabelEncoder
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.utils import to_categorical
import tensorflow as tf
import json
# Load the sample data
csv_filename = "New_data.csv"
data = pd.read_csv(csv_filename)

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32768 entries, 0 to 32767
Data columns (total 11 columns):
 #   Column                    Non-Null Count  Dtype 
---  ------                    --------------  ----- 
 0   Interest                  32768 non-null  object
 1   Fascination               32768 non-null  object
 2   Coursework_Interest       32768 non-null  object
 3   Engineering_Focus         32768 non-null  object
 4   Principles_Application    32768 non-null  object
 5   Specialization_Appeal     32768 non-null  object
 6   Impact_on_Society         32768 non-null  object
 7   Inspiring_Figures         32768 non-null  object
 8   Role_in_Technology        32768 non-null  object
 9   Problem_Solving_Approach  32768 non-null  object
 10  Output                    32768 non-null  object
dtypes: object(11)
memory usage: 2.8+ MB


In [6]:
data.head()

Interest              Fascination  \
0  Electrical Engineering  Smart grid technologies   
1  Electrical Engineering  Smart grid technologies   
2  Electrical Engineering  Smart grid technologies   
3  Electrical Engineering  Smart grid technologies   
4  Electrical Engineering  Smart grid technologies   

               Coursework_Interest                      Engineering_Focus  \
0  Microcontrollers for automation  Power systems and energy distribution   
1  Microcontrollers for automation  Power systems and energy distribution   
2  Microcontrollers for automation  Power systems and energy distribution   
3  Microcontrollers for automation  Power systems and energy distribution   
4  Microcontrollers for automation  Power systems and energy distribution   

            Principles_Application              Specialization_Appeal  \
0  Designing efficient power grids  Telecommunications and networking   
1  Designing efficient power grids  Telecommunications and networking   
2  Designing efficient power grids  Telecommunications and networking   
3  Designing efficient power grids  Telecommunications and networking   
4  Designing efficient power grids  Telecommunications and networking   

  Impact_on_Society Inspiring_Figures      Role_in_Technology  \
0               Yes      Nikola Tesla   Enabling connectivity   
1               Yes      Nikola Tesla   Enabling connectivity   
2               Yes      Nikola Tesla   Enabling connectivity   
3               Yes      Nikola Tesla   Enabling connectivity   
4               Yes      Nikola Tesla  Developing IoT devices   

     Problem_Solving_Approach                                      Output  
0  Analytical problem-solving  Telecommunications and Networking Engineer  
1   Collaborative team effort  Telecommunications and Networking Engineer  
2    Hands-on experimentation  Telecommunications and Networking Engineer  
3            All of the above  Telecommunications and Networking Engineer  
4  Analytical problem-solving  Telecommunications and Networking Engineer

In [7]:
# Split the data into features (X) and labels (y)
X = data.iloc[:, :-1].values
# X

In [8]:
y = data.iloc[:, -1].values
# y

In [9]:
# Use LabelEncoder to encode categorical labels to numerical values
label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(y)

In [10]:
y_encoded

array([55, 55, 55, ..., 25, 25, 25])

In [11]:
label_encoder.inverse_transform(y_encoded)

array(['Telecommunications and Networking Engineer',
       'Telecommunications and Networking Engineer',
       'Telecommunications and Networking Engineer', ...,
       'Graphics Software Engineer', 'Graphics Software Engineer',
       'Graphics Software Engineer'], dtype=object)

**SAVE OUTPUT LABEL ENCODING**

In [17]:
max(y_encoded)

55

In [21]:
label_encoding_dict = {}
for i in range(max(y_encoded)+1):
    Output_lables=label_encoder.inverse_transform([i])
    decoded_label=Output_lables[0]
    # print(decoded_label)

       # Add the mapping to the dictionary
    label_encoding_dict[str(i)] = decoded_label


In [22]:
label_encoding_dict

{'0': ' Consumer Electronics Power Systems Engineer',
 '1': 'Aerospace Engineer',
 '2': 'Analog Signal Processing Engineer',
 '3': 'Automation Engineer',
 '4': 'Automotive Design Engineer',
 '5': 'Biomedical Electronics Engineer',
 '6': 'Cloud Engineer',
 '7': 'Communication Signal Processing Embedded Engineer',
 '8': 'Communication Signal Processing Engineer',
 '9': 'Communication Systems Engineer',
 '10': 'Consumer Electronics Communication Engineer',
 '11': 'Consumer Electronics Embedded Systems Engineer',
 '12': 'Consumer Electronics Semiconductor Engineer',
 '13': 'Consumer Electronics Systems Engineer',
 '14': 'Cybersecurity Engineer',
 '15': 'Data Scientist',
 '16': 'Digital Signal Processing Engineer',
 '17': 'Electronics Communication Engineer',
 '18': 'Electronics Power Systems Engineer',
 '19': 'Electronics Semiconductor Engineer',
 '20': 'Energy Systems Engineer',
 '21': 'Fluid Dynamics Engineer',
 '22': 'Graphics Cloud Engineer',
 '23': 'Graphics Cybersecurity Engineer',
 

In [23]:
# Save label encodings to a JSON file
with open('Output_label_encodings.json', 'w') as json_file:
    json.dump(label_encoding_dict, json_file)

---------------------------------------------

**ENCODE INPUT**

In [24]:
# Use OneHotEncoder to one-hot encode categorical features
onehot_encoder = OneHotEncoder(sparse=False)
X_encoded = onehot_encoder.fit_transform(X)
X_encoded

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


array([[0., 1., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       ...,
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.]])

In [25]:
X_encoded.shape

(32768, 119)

In [26]:
len(X_encoded[0])

119

**SAVE ONEHOT ENCODER**

In [27]:
# Store the feature names and indices mapping
feature_indices_mapping = {str(i): feature_name for i, feature_name in enumerate(data.columns[:-1])}

In [28]:
# Save the categories and feature indices mapping to a JSON file
encoding_info = {
    'categories': {str(i): cats.tolist() for i, cats in enumerate(onehot_encoder.categories_)},
    'feature_indices_mapping': feature_indices_mapping,
}

with open('onehot_encoder_encoding.json', 'w') as json_file:
    json.dump(encoding_info, json_file)

--------------------------------------------------------------------

In [29]:
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X_encoded, to_categorical(y_encoded), test_size=0.2, random_state=42)


In [30]:
# Build a simple neural network model
model = Sequential()

In [31]:
# Input layer
model.add(Dense(256, input_dim=X_train.shape[1], activation='relu'))
# Additional hidden layers with dropout for regularization
model.add(Dense(128, activation='relu'))
model.add(Dropout(0.2))  # Adding dropout for regularization
model.add(Dense(64, activation='relu'))
model.add(Dropout(0.1))  # Adding dropout for regularization

In [ ]:



# model.add(Dense(64, input_dim=X_train.shape[1], activation='relu'))
# model.add(Dense(32, activation='relu'))  # Additional hidden layer
# model.add(Dense(16, activation='relu'))  # Additional hidden layer


In [32]:
model.add(Dense(to_categorical(y_encoded).shape[1], activation='softmax'))  # Output layer with dynamic number of units
# model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.compile(loss='categorical_crossentropy', optimizer=tf.keras.optimizers.Adam(learning_rate=0.001), metrics=['accuracy'])


In [34]:
# Train the model
model.fit(X_train, y_train, epochs=100, batch_size=32, validation_split=0.2)

# Evaluate the model on the test set
loss, accuracy = model.evaluate(X_test, y_test)
print(f"Test Accuracy: {accuracy * 100:.2f}%")

Epoch 1/100
656/656 [==============================] - 5s 7ms/step - loss: 0.0033 - accuracy: 0.9990 - val_loss: 8.1723e-06 - val_accuracy: 1.0000
Epoch 2/100
656/656 [==============================] - 3s 5ms/step - loss: 0.0028 - accuracy: 0.9991 - val_loss: 6.8745e-06 - val_accuracy: 1.0000
Epoch 3/100
656/656 [==============================] - 2s 3ms/step - loss: 9.6352e-04 - accuracy: 0.9999 - val_loss: 5.8973e-07 - val_accuracy: 1.0000
Epoch 4/100
656/656 [==============================] - 2s 3ms/step - loss: 0.0020 - accuracy: 0.9995 - val_loss: 1.1760e-05 - val_accuracy: 1.0000
Epoch 5/100
656/656 [==============================] - 2s 3ms/step - loss: 0.0046 - accuracy: 0.9987 - val_loss: 1.0987e-06 - val_accuracy: 1.0000
Epoch 6/100
656/656 [==============================] - 2s 3ms/step - loss: 5.6575e-04 - accuracy: 0.9999 - val_loss: 2.0809e-07 - val_accuracy: 1.0000
Epoch 7/100
656/656 [==============================] - 2s 3ms/step - loss: 4.6767e-04 - accuracy: 0.9999 - val

In [35]:
# Convert the model to TensorFlow Lite format
converter = tf.lite.TFLiteConverter.from_keras_model(model)
tflite_model = converter.convert()

# Save the TensorFlow Lite model to a file
tflite_filename = "model_final.tflite"
with open(tflite_filename, 'wb') as f:
    f.write(tflite_model)


In [37]:
import numpy as np

In [43]:
new_responses = np.array([['Computer Science Engineering','Cybersecurity',' Machine learning algorithms','Undecided','Designing efficient hardware for AI and blockchain','Data science and analytics','No','Alan Turing','Designing novel hardware architectures','Agile development methodology']])
new_responses_encoded = onehot_encoder.transform(new_responses)
new_responses_encoded

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
        0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
        0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
        0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
        0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
new_responses_encoded= [[1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 1, 0]]

In [44]:
result=model.predict(new_responses_encoded)

1/1 [==============================] - 0s 30ms/step


In [45]:
result

array([[0.00000000e+00, 0.00000000e+00, 6.58712382e-37, 3.45590834e-38,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        1.01238114e-32, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 1.98945482e-26, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 3.04249766e-37, 2.07829755e-36, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 1.98864234e-34, 3.72462622e-33, 1.00000000e+00,
        2.23962967e-34, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 2.15500716e-33, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 4.96406621e-32,
        0.00000000e+00, 0.00000000e+00, 6.36617067e-37, 0.00000000e+00,
        0.00000000e+00, 3.27240840e-33, 0.00000000e+00, 0.000000

In [46]:
# Decode the predicted label
predicted_label_encoded = np.argmax(result)
predicted_label_encoded

35

In [47]:
predicted_label = label_encoder.classes_[predicted_label_encoded]
predicted_label

'Machine Learning Engineer'

TRY INFERENCE

In [48]:
import numpy as np
import tensorflow as tf
from sklearn.preprocessing import OneHotEncoder, LabelEncoder
# Load the TensorFlow Lite model
tflite_filename = "model_final.tflite"
interpreter = tf.lite.Interpreter(model_path=tflite_filename)
interpreter.allocate_tensors()

In [49]:

# Get input and output tensors
input_details = interpreter.get_input_details()
input_details


[{'name': 'serving_default_dense_input:0',
  'index': 0,
  'shape': array([  1, 119], dtype=int32),
  'shape_signature': array([ -1, 119], dtype=int32),
  'dtype': numpy.float32,
  'quantization': (0.0, 0),
  'quantization_parameters': {'scales': array([], dtype=float32),
   'zero_points': array([], dtype=int32),
   'quantized_dimension': 0},
  'sparsity_parameters': {}}]

In [50]:
output_details = interpreter.get_output_details()
output_details

[{'name': 'StatefulPartitionedCall:0',
  'index': 13,
  'shape': array([ 1, 56], dtype=int32),
  'shape_signature': array([-1, 56], dtype=int32),
  'dtype': numpy.float32,
  'quantization': (0.0, 0),
  'quantization_parameters': {'scales': array([], dtype=float32),
   'zero_points': array([], dtype=int32),
   'quantized_dimension': 0},
  'sparsity_parameters': {}}]

In [51]:
# Assuming you have a new set of responses to 10 questions for inference
new_responses = np.array([['Computer Science Engineering','Cybersecurity',' Machine learning algorithms','Undecided','Designing efficient hardware for AI and blockchain','Data science and analytics','No','Alan Turing','Designing novel hardware architectures','Agile development methodology']])
new_responses_encoded = onehot_encoder.transform(new_responses)
new_responses_encoded

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
        0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
        0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
        0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
        0., 0., 0., 0., 0., 0., 0.]])

In [52]:
new_responses_encoded

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
        0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
        0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
        0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
        0., 0., 0., 0., 0., 0., 0.]])

In [53]:
new_responses_encoded.shape

(1, 119)

In [54]:
interpreter.set_tensor(input_details[0]['index'], new_responses_encoded.astype(np.float32))
interpreter.invoke()

In [55]:
# Get the output
output_data = interpreter.get_tensor(output_details[0]['index'])
output_data

array([[0.00000000e+00, 0.00000000e+00, 6.58712338e-37, 3.45588227e-38,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        1.01238885e-32, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 1.98945482e-26, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 3.04249743e-37, 2.07828176e-36, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 1.98864234e-34, 3.72462622e-33, 1.00000000e+00,
        2.23966365e-34, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 2.15502351e-33, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 4.96410442e-32,
        0.00000000e+00, 0.00000000e+00, 6.36621910e-37, 0.00000000e+00,
        0.00000000e+00, 3.27240840e-33, 0.00000000e+00, 0.000000

In [56]:
# Decode the predicted label
predicted_label_encoded = np.argmax(output_data)
predicted_label_encoded

35

In [57]:
predicted_label = label_encoder.classes_[predicted_label_encoded]
predicted_label

'Machine Learning Engineer'

**TRY TO SAVE ENCODINGS**

In [ ]:
import joblib
# Save the OneHotEncoder to a file
encoder_filename = "onehot_encoder.joblib"
joblib.dump(onehot_encoder, encoder_filename)

['onehot_encoder.joblib']

TO LOAD

In [ ]:
import joblib
# Later, for inference, load the OneHotEncoder back
loaded_onehot_encoder = joblib.load('onehot_encoder.joblib')

In [ ]:
# Now, you can use the loaded_onehot_encoder for transforming new data
new_data = pd.DataFrame([
    ['Electronics','Advanced communication systems','Embedded systems programming for robotics','Digital electronics and microcontrollers','All of the above','Robotics and automation','Yes','Elon Musk','Innovating in multi-disciplinary technologies','All of the above']
], columns=data.columns[:-1])

new_encoded_data = loaded_onehot_encoder.transform(new_data)


/usr/local/lib/python3.10/dist-packages/sklearn/base.py:432: UserWarning: X has feature names, but OneHotEncoder was fitted without feature names
  warnings.warn(


In [ ]:
new_encoded_data

array([[0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0.,
        0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 1., 1., 0., 0.]])

In [ ]:
new_data

Interest                     Fascination  \
0  Electronics  Advanced communication systems   

                         Coursework_Interest  \
0  Embedded systems programming for robotics   

                          Engineering_Focus Principles_Application  \
0  Digital electronics and microcontrollers       All of the above   

     Specialization_Appeal Impact_on_Society Inspiring_Figures  \
0  Robotics and automation               Yes         Elon Musk   

                              Role_in_Technology Problem_Solving_Approach  
0  Innovating in multi-disciplinary technologies         All of the above

**TO SAVE FOR ANDROID**

In [ ]:
# Store the feature names and indices mapping
feature_indices_mapping = {str(i): feature_name for i, feature_name in enumerate(data.columns[:-1])}


In [ ]:
# Save the categories and feature indices mapping to a JSON file
encoding_info = {
    'categories': {str(i): cats.tolist() for i, cats in enumerate(onehot_encoder.categories_)},
    'feature_indices_mapping': feature_indices_mapping,
}

with open('/content/onehot_encoder_encoding.json', 'w') as json_file:
    json.dump(encoding_info, json_file)